<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>monsterland</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="entities\player\" />
  </ItemGroup>
</Project>